// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: gconf.proto

package gconf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_HEARTBEAT MsgType = 0
	MsgType_SITUATION MsgType = 1
	MsgType_TASK      MsgType = 2
	MsgType_FILE      MsgType = 3
	MsgType_COMMAND   MsgType = 4
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "HEARTBEAT",
		1: "SITUATION",
		2: "TASK",
		3: "FILE",
		4: "COMMAND",
	}
	MsgType_value = map[string]int32{
		"HEARTBEAT": 0,
		"SITUATION": 1,
		"TASK":      2,
		"FILE":      3,
		"COMMAND":   4,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_gconf_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_gconf_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_gconf_proto_rawDescGZIP(), []int{0}
}

type PBMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int32  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Node      string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Label     string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Version   string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Hash      string `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Raw       []byte `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *PBMessage) Reset() {
	*x = PBMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gconf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBMessage) ProtoMessage() {}

func (x *PBMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gconf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBMessage.ProtoReflect.Descriptor instead.
func (*PBMessage) Descriptor() ([]byte, []int) {
	return file_gconf_proto_rawDescGZIP(), []int{0}
}

func (x *PBMessage) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PBMessage) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PBMessage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PBMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PBMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PBMessage) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type PBFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PBFile) Reset() {
	*x = PBFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gconf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBFile) ProtoMessage() {}

func (x *PBFile) ProtoReflect() protoreflect.Message {
	mi := &file_gconf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBFile.ProtoReflect.Descriptor instead.
func (*PBFile) Descriptor() ([]byte, []int) {
	return file_gconf_proto_rawDescGZIP(), []int{1}
}

func (x *PBFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PBFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_gconf_proto protoreflect.FileDescriptor

var file_gconf_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x63, 0x6f, 0x6e, 0x66, 0x22, 0x93, 0x01, 0x0a, 0x09, 0x50, 0x42, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x36, 0x0a, 0x06, 0x50, 0x42,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x2a, 0x48, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x49, 0x54, 0x55, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54,
	0x41, 0x53, 0x4b, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x10, 0x04, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x67, 0x63, 0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gconf_proto_rawDescOnce sync.Once
	file_gconf_proto_rawDescData = file_gconf_proto_rawDesc
)

func file_gconf_proto_rawDescGZIP() []byte {
	file_gconf_proto_rawDescOnce.Do(func() {
		file_gconf_proto_rawDescData = protoimpl.X.CompressGZIP(file_gconf_proto_rawDescData)
	})
	return file_gconf_proto_rawDescData
}

var file_gconf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gconf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gconf_proto_goTypes = []interface{}{
	(MsgType)(0),      // 0: gconf.MsgType
	(*PBMessage)(nil), // 1: gconf.PBMessage
	(*PBFile)(nil),    // 2: gconf.PBFile
}
var file_gconf_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gconf_proto_init() }
func file_gconf_proto_init() {
	if File_gconf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gconf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gconf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gconf_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gconf_proto_goTypes,
		DependencyIndexes: file_gconf_proto_depIdxs,
		EnumInfos:         file_gconf_proto_enumTypes,
		MessageInfos:      file_gconf_proto_msgTypes,
	}.Build()
	File_gconf_proto = out.File
	file_gconf_proto_rawDesc = nil
	file_gconf_proto_goTypes = nil
	file_gconf_proto_depIdxs = nil
}
